package br.com.board;

import java.sql.SQLException;

import static br.com.board.persistence.config.ConnectionConfig.getConnection;
import br.com.board.persistence.migration.MigrationStrategy;
import br.com.board.ui.MainMenu;

/*
 * This source file was generated by the Gradle 'init' task
 */
public class App {

    public static void main(String[] args) throws SQLException {
        try (var connection = getConnection()) {
            new MigrationStrategy(connection).executeMigration();
        }
        new MainMenu().execute();
    }
}
